### PR TITLE
Prepare train command

### PR DESCRIPTION
**Pull request by ivyleavedtoadflax**
Prepare the train script for use on the command line. and other minor fixes.

Please use this as an opportunity to review the package as it is. Some sensible tests would be:

```
# Run tests (this will dl some artefacts first)
make test

# Create a test file:

cat > references.txt <<EOF
1 Sibbald, A, Eason, W, McAdam, J, and Hislop, A (2001). The establishment phase of a silvopastoral national network experiment in the UK. Agroforestry systems, 39, 39–53. 
2 Silva, J and Rego, F (2003). Root distribution of a Mediterranean shrubland in Portugal. Plant and Soil, 255 (2), 529–540. 
3 Sims, R, Schock, R, Adegbululgbe, A, Fenhann, J, Konstantinaviciute, I, Moomaw, W, Nimir, H, Schlamadinger, B, Torres-Martínez, J, Turner, C, Uchiyama, Y, Vuori, S, Wamukonya, N, and X. Zhang (2007). Energy Supply. In Metz, B, Davidson, O, Bosch, P, Dave, R, and Meyer, L (eds.), Climate Change 2007: Mitigation. Contribution of Working Group III to the Fourth Assessment Report of the Intergovernmental Panel on Climate Change, Cambridge University Press, Cambridge, United Kingdom and New York, NY, USA.
EOF

# Test the default model that ships with the package in a new venv
virtualenv temp && source temp/bin/activate
pip install git+git://github.com/wellcometrust/deep_reference_parser.git#egg=deep_reference_parser
python -m deep_reference_parser predict --verbose "$(cat references.txt)"

# Get some data to train the model

make data

# Create your own config and try to train a model
cat > testme.ini <<EOF
[DEFAULT]
version = testme

[data]
test_proportion = 0.25
valid_proportion = 0.25
data_path = data/
respect_line_endings = 0
respect_doc_endings = 1
line_limit = 100
policy_train = data/2019.12.0_valid.tsv
policy_test = data/2019.12.0_valid.tsv
policy_valid = data/2019.12.0_valid.tsv
s3_slug = https://datalabs-public.s3.eu-west-2.amazonaws.com/deep_reference_parser/

[build]
output_path = models/testme/
output = crf
word_embeddings = embeddings/2020.1.1-wellcome-embeddings-300.txt
pretrained_embedding = 0
dropout = 0
lstm_hidden = 100
word_embedding_size = 300
char_embedding_size = 100
char_embedding_type = BILSTM
optimizer = rmsprop

[train]
epochs = 1
batch_size = 100
early_stopping_patience = 5
metric = val_f1

[evaluate]
out_file = evaluation_data.tsv
EOF

python -m deep_reference_parser train testme.ini

# cleanup
rm -r temp testme.ini references.txt
```

### CODE REVIEW

**Comment by lizgzil** [comment]
I've done
```
make virtualenv

# Run tests (this will dl some artefacts first)
make test

# Create a test file:

cat > references.txt <<EOF
1 Sibbald, A, Eason, W, McAdam, J, and Hislop, A (2001). The establishment phase of a silvopastoral national network experiment in the UK. Agroforestry systems, 39, 39–53. 
2 Silva, J and Rego, F (2003). Root distribution of a Mediterranean shrubland in Portugal. Plant and Soil, 255 (2), 529–540. 
3 Sims, R, Schock, R, Adegbululgbe, A, Fenhann, J, Konstantinaviciute, I, Moomaw, W, Nimir, H, Schlamadinger, B, Torres-Martínez, J, Turner, C, Uchiyama, Y, Vuori, S, Wamukonya, N, and X. Zhang (2007). Energy Supply. In Metz, B, Davidson, O, Bosch, P, Dave, R, and Meyer, L (eds.), Climate Change 2007: Mitigation. Contribution of Working Group III to the Fourth Assessment Report of the Intergovernmental Panel on Climate Change, Cambridge University Press, Cambridge, United Kingdom and New York, NY, USA.
EOF

# Test the default model that ships with the package in a new venv
virtualenv temp && source temp/bin/activate
pip install git+git://github.com/wellcometrust/deep_reference_parser.git#egg=deep_reference_parser
python -m deep_reference_parser predict --verbose "$(cat references.txt)"
```
Which were all fine apart from the last command which gave the errors:
```
⠙ Could not find char2ind.pickle locally, downloading...✘ Could not download models/2020.2.0/char2ind.pickle

Traceback (most recent call last):
  File "/Users/gallaghe/Code/deep_reference_parser/deep_reference_parser/predict.py", line 51, in __init__
    download_model_artefact(artefact, S3_SLUG)
  File "/Users/gallaghe/Code/deep_reference_parser/deep_reference_parser/common.py", line 39, in download_model_artefact
    request.urlretrieve(url, artefact)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/gallaghe/Code/deep_reference_parser/deep_reference_parser/__main__.py", line 26, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/Users/gallaghe/Code/deep_reference_parser/temp/lib/python3.7/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/gallaghe/Code/deep_reference_parser/temp/lib/python3.7/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/gallaghe/Code/deep_reference_parser/deep_reference_parser/predict.py", line 162, in predict
    predictor = Predictor(config_file)
  File "/Users/gallaghe/Code/deep_reference_parser/deep_reference_parser/predict.py", line 55, in __init__
    logger.exception()
TypeError: exception() missing 1 required positional argument: 'msg'
```

I guess it doesn't like
```
url = parse.urljoin(s3_slug, artefact)
request.urlretrieve(url, artefact)
```
when I print s3_slug I get `s3_slug = https://datalabs-public.s3.eu-west-2.amazonaws.com/deep_reference_parser/ ` which I guess is incorrect?

**Comment by ivyleavedtoadflax** [comment]
Thanks @lizgzil . That's very strange, the S3 slug looks ok, and it works on Travis. Might be an intermittent connection issue. Could you try that last command again?

**Comment by lizgzil** [comment]
@ivyleavedtoadflax i tried again and it had the same issue

**Comment by ivyleavedtoadflax** [comment]
> LGTM. Your examples of things to run in the PR description all ran and the predicted references look

Thanks @lizgzil !

**Pull request merged**
